// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvgomxzhzevixmcktcao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2Z29teHpoemV2aXhtY2t0Y2FvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MDU5MjEsImV4cCI6MjA3MzI4MTkyMX0.kT5ehre8eLfqBYTZpxtY5gByBoMlFamGFUE179UXaLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});